#!/usr/bin/python

from typing import Any
from tempfile import TemporaryFile as TempFile
import subprocess
import rich
import ctypes


def cmd(command: list[Any], std_in: str='') -> tuple[int, str]:
    command_str = list(map(str, command))
    with TempFile() as stdin, TempFile() as stdout:
        stdin.write(std_in.encode('utf-8'))
        stdin.seek(0)

        result = subprocess.run(command_str, stdin=stdin, stdout=stdout)

        stdout.seek(0)
        output = stdout.read().decode('utf-8')

        return result.returncode, output


if __name__ == '__main__':
    pass